# Generated by Django 6.0.5 on 2026-05-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('bibit', 'Bibit'), ('pupuk', 'Pupuk'), ('lainnya', 'Lainnya')], max_length=20)),
                ('satuan', models.CharField(help_text='contoh: kg, liter, batang, karung', max_length=30)),
                ('stok', models.FloatField(default=0)),
                ('harga_beli', models.FloatField(default=0, help_text='Harga beli per satuan (Rp)')),
                ('keterangan', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MutasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
                ('jumlah', models.FloatField()),
                ('harga_sat', models.FloatField(default=0, help_text='Harga per satuan saat mutasi')),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi', to='stok.stok')),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
