# Generated by Django 6.0.5 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengeluaranLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('operasional', 'Operasional'), ('peralatan', 'Peralatan'), ('transport', 'Transport'), ('lainnya', 'Lainnya')], default='operasional', max_length=20)),
                ('deskripsi', models.CharField(max_length=200)),
                ('jumlah', models.FloatField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
