# Generated by Django 6.0.5 on 2026-05-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jabatan', models.CharField(blank=True, default='', max_length=100)),
                ('no_hp', models.CharField(blank=True, default='', max_length=20)),
                ('alamat', models.TextField(blank=True, default='')),
                ('gaji_pokok', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('gaji_pokok', models.FloatField()),
                ('tunjangan', models.FloatField(default=0)),
                ('potongan', models.FloatField(default=0)),
                ('total_gaji', models.FloatField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('tanggal_bayar', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggajian', to='pegawai.pegawai')),
            ],
            options={
                'ordering': ['-periode', '-id'],
                'unique_together': {('pegawai', 'periode')},
            },
        ),
    ]
