# Generated by Django 6.0.5 on 2026-05-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('no_faktur', models.CharField(max_length=60, unique=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=150)),
                ('total', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('no_faktur', models.CharField(max_length=60, unique=True)),
                ('pembeli', models.CharField(blank=True, default='', max_length=150)),
                ('total', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=150)),
                ('jumlah', models.FloatField()),
                ('satuan', models.CharField(max_length=30)),
                ('harga_sat', models.FloatField()),
                ('stok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stok.stok')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=150)),
                ('jumlah', models.FloatField()),
                ('satuan', models.CharField(max_length=30)),
                ('harga_sat', models.FloatField()),
                ('harga_beli', models.FloatField(default=0, help_text='HPP saat dijual')),
                ('stok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stok.stok')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi.penjualan')),
            ],
        ),
    ]
